import Head from 'next/head';
import Image from 'next/image';

import { evaluate } from 'mathjs';

import { useState, useEffect } from 'react';

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faBackspace, faDivide, faEquals, faMinus, faPercent, faPlus, faTimes, faTrash } from '@fortawesome/free-solid-svg-icons';

import Swal from 'sweetalert2';
import withReactContent from 'sweetalert2-react-content';

export default function Home() {
  const [result, setResult] = useState('');
  const [expression, setExpression] = useState('expression');
  const [answer, setAnswer] = useState('');

  const MySwal = withReactContent(Swal);

  const onButtonClick = (e) => {
    setResult((prev) => {
      return prev + e.target.innerHTML;
    });
  };

  const clearDisplay = () => {
    setResult('');
  };

  const onBackspace = () => {
    const expression = result;

    setResult((prev) => expression.slice(0, -1));
  };

  const calculateResult = async () => {
    const expression = result;
    try {
      const ans = await evaluate(expression);
      setAnswer(ans);
    } catch (err) {
      MySwal.fire({
        title: <p>Hello World</p>,
        didOpen: () => {
          // `MySwal` is a subclass of `Swal` with all the same instance & static methods
          MySwal.showLoading();
        },
      }).then(() => {
        return MySwal.fire(<p>Shorthand works too</p>);
      });
    }
  };

  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="main">
        <section className="display">
          <span className="expression">{result}</span>
          <span className="answer">Ans:{answer}</span>
        </section>

        <div className="container">
          <button className="key trash keymod" onClick={clearDisplay}>
            <FontAwesomeIcon icon={faTrash} />
          </button>
          <button className="key percent keymod">
            <FontAwesomeIcon icon={faPercent} />
          </button>
          <button className="key backspace keymod" onClick={onBackspace}>
            <FontAwesomeIcon icon={faBackspace} />
          </button>
          <button className="key divide keymod" onClick={onButtonClick}>
            {/* <FontAwesomeIcon icon={faDivide} /> */}/
          </button>
        </div>

        <div className="container">
          <button className="key seven numkey" onClick={onButtonClick}>
            7
          </button>
          <button className="key eight numkey" onClick={onButtonClick}>
            8
          </button>
          <button className="key nine numkey" onClick={onButtonClick}>
            9
          </button>
          <button className="key keymod multiply" onClick={onButtonClick}>
            {/* <FontAwesomeIcon icon={faTimes} /> */}*
          </button>
        </div>

        <div className="container">
          <button className="key four numkey" onClick={onButtonClick}>
            4
          </button>
          <button className="key five numkey" onClick={onButtonClick}>
            5
          </button>
          <button className="key six numkey" onClick={onButtonClick}>
            6
          </button>
          <button className="key keymod minus" onClick={onButtonClick}>
            {/* <FontAwesomeIcon icon={faMinus} /> */}-
          </button>
        </div>

        <div className="container">
          <button className="key one numkey" onClick={onButtonClick}>
            1
          </button>
          <button className="key two numkey" onClick={onButtonClick}>
            2
          </button>
          <button className="key three numkey" onClick={onButtonClick}>
            3
          </button>
          <button className="key keymod add" onClick={onButtonClick}>
            {/* <FontAwesomeIcon icon={faPlus} /> */}+
          </button>
        </div>

        <div className="container">
          <button className="key null numkey"></button>
          <button className="key zero numkey" onClick={onButtonClick}>
            0
          </button>
          <button className="key dot numkey">
            <i className="fas fa-circle"></i>
          </button>
          <button className="key keymod equals" onClick={calculateResult}>
            <FontAwesomeIcon icon={faEquals} />
          </button>
        </div>
      </section>
    </div>
  );
}
